apiVersion: v1
kind: Service
metadata:
  name: fixmate-frontend-service
  namespace: fixmate
spec:
  selector:
    app: fixmate-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 